// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ls_env
std::vector<std::string> ls_env();
RcppExport SEXP envmunge_ls_env() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        std::vector<std::string> __result = ls_env();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// replace
void replace(int index, std::string name, std::string value);
RcppExport SEXP envmunge_replace(SEXP indexSEXP, SEXP nameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type index(indexSEXP );
        Rcpp::traits::input_parameter< std::string >::type name(nameSEXP );
        Rcpp::traits::input_parameter< std::string >::type value(valueSEXP );
        replace(index, name, value);
    }
    return R_NilValue;
END_RCPP
}
// unset
void unset(std::vector<bool> indices);
RcppExport SEXP envmunge_unset(SEXP indicesSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::vector<bool> >::type indices(indicesSEXP );
        unset(indices);
    }
    return R_NilValue;
END_RCPP
}
// fix_yosemite_bug
void fix_yosemite_bug();
RcppExport SEXP envmunge_fix_yosemite_bug() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        fix_yosemite_bug();
    }
    return R_NilValue;
END_RCPP
}
