# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ls_env <- function() {
    .Call('envmunge_ls_env', PACKAGE = 'envmunge')
}

replace <- function(index, name, value) {
    invisible(.Call('envmunge_replace', PACKAGE = 'envmunge', index, name, value))
}

unset <- function(indices) {
    invisible(.Call('envmunge_unset', PACKAGE = 'envmunge', indices))
}

fix_yosemite_bug <- function() {
    invisible(.Call('envmunge_fix_yosemite_bug', PACKAGE = 'envmunge'))
}

